### ISSUE TITLE
Add option to sort items in default view by title

### ISSUE THREAD

**Issue by elkoniu** [turtl/tracker#306] opened 2019-04-01 14:34 UTC
It could be nice to be able to minimize all notes content and shrink them just to title. Then be able to display it in alphabetical / age order. Sometime searching through notes via search tool is overkill. Many peoples keeps similar notes with tittle starting with the same keyword like "Linux...", "Config of ..." etc.

**Comment by orthecreedence** [comment] 2019-04-04 01:55
Hi, I think this is a duplicate of #220. Also, minimizing note content will be accomplished with #36!

**Closed as completed by orthecreedence** 2019-04-04 01:55 UTC
