### ISSUE TITLE
OSX firefox add-on: can't paste pairing code in add-on popup window

### ISSUE THREAD

**Issue by maxf** [turtl/tracker#253] opened 2018-12-04 10:55 UTC
This is on latest OSX
steps:
- install desktop app
- install firefox add-on
- click on turtl icon in browser: desktop app pairing window pops up with code to copy paste (by the way that window pops up in front of the browser popup, so it's a bit confusing)
- copy the code
- go back to browser
- when clicking on the text field in order to give it focus before pasting, it just goes away so there's nothing to paste into. 
- Expected: it should stay there and let the user paste the code into it.
- clicking again on the add-on icon randomly shows the popup again (with the same behaviour) or does nothing at all

**Comment by orthecreedence** [comment] 2018-12-07 06:03
This is (almost certainly) a duplicate of #218. It's mostly due to a bug in the way the extensions work, and we're looking into a fix. Thanks!

**Closed as completed by orthecreedence** 2018-12-07 06:03 UTC
