### ISSUE TITLE
Note's contents search feature request

### ISSUE THREAD

**Issue by l4mbd0x** [turtl/tracker#158] opened 2018-09-16 21:59 UTC
While it's ok to no have this feature for short notes (no bigger than 100 lines), when it becomes bigger than that, it becomes a really waste of time to scroll down to a specific content of the note. Specially if you remember that you took note of it, but are not exactly sure of the location of the annotation within that specific note. This search button would exist for both the visualization and the edit mode of for any specific note, enabling the user to quick find what he/she wants and also to fast jump to another known section of the contents for editing while inside the edit mode of that specific note. This is valid for all platforms and has to do with UX. Please that this in regard.
That aspect was noticed as required by me as I have some notes which are 5000 lines long while using the latest release candidate of 0.7x series of releases.

Thanks for your time.

**Comment by orthecreedence** [comment] 2018-09-17 05:40
I believe this is a duplicate of https://github.com/turtl/tracker/issues/18.

The idea is you could type `ctrl+f` (like in a browser) and be able to search the text that is currently being displayed. I think this would solve your issue once it is completed!

**Closed as completed by orthecreedence** 2018-09-17 05:40 UTC

**Comment by l4mbd0x** [comment] 2018-09-17 14:31
Indeed it would, nice :).
