### ISSUE TITLE
Current status and best way to upgrade

### ISSUE THREAD

**Issue by popindavibe** [turtl/tracker#233] opened 2018-11-06 07:36 UTC
Hello,

Apologies if this was already asked, but I have been following updates on the new client version, and I can see that there is also a 'new server' for Turtl.

How does everything work together? Is the new client compatible with the old server? What should be updated/upgraded first? Looking at the new server the whole backbend has changed, how do I migrate my users' notes?

I am very happy with all the work that went into releasing the new client version and I am eager to migrate, just want to do it the 'right way'. I would be happy to contribute to a documentation or tutorial to do that (as part of the Wiki?).

**Comment by orthecreedence** [comment] 2018-11-06 08:05
Hi, Jean. Thanks for asking.

So here are the steps for upgrading:

1. Get the [new server running](https://github.com/turtl/server)
2. Leave the old server running
3. Upgrade all clients to the new version (v0.7.2+, the later the better, because a lot of migration/login fixes have happened).
4. (For each user) On all of the clients, on the login screen, open "Advanced settings" and update the servers to point at the old server URL and the new server URL (these get cleared out by the upgrade, unfortunately).
5. (For each user) Log in with the old login information. The old login will be detected and they will be prompted to migrate their account by creating a new account (with a new email/password). The email/password *can* be the same as the old one, but this seems to make things more confusing for people so I'd recommend using a new password.
6. Once migrated, the user will then begin using their *new* email/password (not the old v0.6 one).

Things to keep in mind:
- Shares are *not* migrated. You must re-share data once the account is migrated.
- Only notes owned by the user are migrated. In other words, if a board is shared with me, and I migrate, only the notes that I created in that board will be moved over (the other notes will be moved when the user that created them migrates).
- v0.7 clients *cannot* interact with the v0.6 server, except to migrate accounts.
- If one client is v0.7 and one is v0.6, the data will become out of sync...all clients must be upgraded at the same time.
- The migration process doesn't actually change anything on the old server, it just copies data and reformats it for the new server.
- If a user has trouble migrating, many times deleting their *new* account and retrying the migration will work (this is rare but I've seen it happen and usually the second time around works great).
- If a user needs help manually deleting their account, there's a script for that: `node turtl/server/tools/delete_user.js <email or id>`

I *think* that should cover everything. Feel free to ask if anything comes up! I'm going to close this issue for now, but will continue to respond.

**Closed as completed by orthecreedence** 2018-11-06 08:05 UTC
Labels: project:server, type:question

**Comment by popindavibe** [comment] 2018-11-06 08:34
Thanks, very appreciated. I'll follow this carefully and will update here if needed.

**Comment by popindavibe** [comment] 2018-11-23 23:18
Hi Andrew,
Everything worked out pretty well, I have reorganized my boards to adapt to the new structure (using 'spaces' + boards instead of  boards + sub-boards).

However I am trying to understand what/how should be handled the confirmation email upon inscription:
- What should `www_url` be? 
I set it to an alias of my api URL, but as expected it's not really user-friendly and display an auth error when the link opens a json page in the browser (though I _do_ reach the success URL). Is the server supposed to somehow handle anything else than API requests and for sharing confirmation show a proper HTML response instead of JSON?

- Second question, is there a way to somehow lock new registration or enforce validation before activation? While I am planning to make my instance public, I would like to be able to keep a minimum of control over it.

**Comment by orthecreedence** [comment] 2018-11-28 04:17
Hi, Jean.

- `www_url` for our live instance is `https://turtlapp.com`. This gives the API somewhere to direct users when they have successfully confirmed, and I think may be used in one or two other places (a `grep -lr 'www_url' . --exclude-dir=node_modules --exclude-dir=.git` in the `server/` directory will tell you what files use this value and you can search within them to find exactly what). Then you'd need to have a website you can direct users to that has an endpoint for each one of those redirects.
- Right now, no. However, I've been getting a lot of requests for this, so what I might do is give user registration a plugin that can be tied into, and you could set the user to `active=false` until you hand-approve them (or something like that). Added this: #250

**Comment by popindavibe** [comment] 2018-12-24 16:00
Thanks! I provided URLs for:
- /users/confirm/error/
- /users/confirm/success/
on my main website and all is well now. I'll follow up in #250 as it is definitely a feature I'm interested in.
Cheers.
