### ISSUE TITLE
rc4 openssl verify error

### ISSUE THREAD

**Issue by aptmiguk** [turtl/tracker#134] opened 2018-08-10 11:42 UTC
Hi,

Not sure if this is one of the known openssl issues, but on Fedora 28 (x64) I'm getting this when trying to log in:

``
Login failed - Error: An error in the OpenSSL library:certificate verify failed
``
![turtl-openssl-error](https://user-images.githubusercontent.com/39675808/43956088-663947ca-9c68-11e8-8103-12a03ebdf917.png)

I ran it with the commandline as well, but it didn't give much more info:

2018-08-10T06:35:37 - [INFO][turtl_core] main::init() -- created data folder: /home/foo/.config/Turtl/core
2018-08-10T06:35:37 - [INFO][turtl_core] main::start() -- begin
2018-08-10T06:35:37 - [INFO][turtl_core::messaging] messaging::start() -- main loop
2018-08-10T06:35:37 - [INFO][turtl_core::messaging] messaging::ui_event() -- messaging:ready
2018-08-10T06:35:38 - [INFO][turtl_core::dispatch] dispatch(1): app:api:set-endpoint
2018-08-10T06:35:38 - [INFO][turtl_core::dispatch] dispatch(2): app:api:get-endpoint
2018-08-10T06:35:38 - [INFO][turtl_core::dispatch] dispatch(3): app:api:get-old-endpoint
2018-08-10T06:35:58 - [INFO][turtl_core::dispatch] dispatch(4): app:api:set-endpoint
2018-08-10T06:35:58 - [INFO][turtl_core::dispatch] dispatch(5): app:api:set-old-endpoint
2018-08-10T06:35:59 - [INFO][turtl_core::dispatch] dispatch(6): user:login
2018-08-10T06:35:59 - [INFO][turtl_core::models::user] user::generate_auth() -- generating v0 auth
2018-08-10T06:36:28 - [INFO][turtl_core::dispatch] dispatch(7): app:api:set-endpoint
2018-08-10T06:36:28 - [INFO][turtl_core::dispatch] dispatch(8): app:api:set-old-endpoint
2018-08-10T06:36:28 - [INFO][turtl_core::dispatch] dispatch(9): user:login
2018-08-10T06:36:28 - [INFO][turtl_core::models::user] user::generate_auth() -- generating v0 auth

**Comment by orthecreedence** [comment] 2018-08-11 17:43
This is a dupe of the (now fixed) #131

**Closed as completed by orthecreedence** 2018-08-11 17:43 UTC
