### ISSUE TITLE
Failed Connection behind proxy

### ISSUE THREAD

**Issue by MaxCreeger32** [turtl/tracker#153] opened 2018-09-07 07:22 UTC
Hello I am using the turtl desktop RC-9 for windows 10 and compare to the latest stable version (0.6.4), I have connection issues.  
 - At home , no proxy ==> All good
 - At work , proxy ==> os error 10060
![turtl_failed_connection](https://user-images.githubusercontent.com/31531494/45204240-e442b300-b27e-11e8-8e17-7e84f42d9ce7.PNG)

I have not any log in any directories of turtl (AppData/Roaming, AppData/Local, Program Files/Turtl)  

Is there any way of configuring the proxy settings for this version ?

**Comment by orthecreedence** [comment] 2018-09-10 00:22
There is no way of configuring proxy settings through the app currently. How is the work proxy set up? Is this a system-wide proxy? And was there any special setup you did with v0.6.4 that you can remember?

On your work computer, are you able to access https://apiv3.turtlapp.com/ ?

Thank you for your help in tracking this down.

**Comment by MaxCreeger32** [comment] 2018-09-10 06:42
with the browser,  It seems that API url is accessible beacause i have this resulting JSON :  ```{"greeting":"Hi."}```   
I am sorry I have no idea how the proxy works, there is no configuration in the browser or in the internet preferences of the computer.   
In v0.6.4, I did not do anything for the proxy configuration.
Is there a way to activate some logs to see what happens more precisely ?

**Comment by orthecreedence** [comment] 2018-09-11 14:18
There should be a log at `c:\Users\<username>\AppData\Roaming\Turtl\core\core.log`. If you post the contents, it might help debug a bit. Thanks!

**Comment by MaxCreeger32** [comment] 2018-09-11 14:27
This is the only log I have into this file : 
`2018-09-11T16:22:45 - [INFO][turtl_core] main::init() -- created data folder: C:\Users\datas\AppData\Roaming\Turtl\core
2018-09-11T16:22:45 - [INFO][turtl_core] main::start() -- begin
2018-09-11T16:22:45 - [INFO][turtl_core::messaging] messaging::start() -- main loop
2018-09-11T16:22:45 - [INFO][turtl_core::messaging] messaging::ui_event() -- messaging:ready
2018-09-11T16:22:45 - [INFO][turtl_core::dispatch] dispatch(1): app:api:set-endpoint
2018-09-11T16:22:45 - [INFO][turtl_core::dispatch] dispatch(2): app:api:get-endpoint
2018-09-11T16:22:45 - [INFO][turtl_core::dispatch] dispatch(3): app:api:get-old-endpoint
2018-09-11T16:23:05 - [INFO][turtl_core::dispatch] dispatch(4): app:api:set-endpoint
2018-09-11T16:23:05 - [INFO][turtl_core::dispatch] dispatch(5): app:api:set-old-endpoint
2018-09-11T16:23:05 - [INFO][turtl_core::dispatch] dispatch(6): user:login
2018-09-11T16:23:05 - [INFO][turtl_core::models::user] user::generate_auth() -- generating v0 auth
`
Is there any way to set DEBUG level ?

**Comment by orthecreedence** [comment] 2018-09-15 07:57
Yeah there is. You'd go to `C:\Program Files\Turtl\resources\app\build`, edit `config.yaml` and set the log level to `DEBUG`:

```yaml
logging:
  level: 'DEBUG'
```

**Comment by MaxCreeger32** [comment] 2018-09-24 07:16
I have tried many times but, I still no have any debug infos in the logs.
I have set the logging level to debug in ```config.yaml``` but it has absolutely no effect in the log.

**Comment by orthecreedence** [comment] 2018-09-25 04:43
Do you have a firewall that could be blocking the connection?

**Comment by MaxCreeger32** [comment] 2018-10-03 06:51
I have verified the windows firewall on my computer but everything is ok. and the only thing that can block is the proxy that is set for all the company but via the browser the url is accessible.

**Comment by orthecreedence** [comment] 2018-10-05 05:19
Can you confirm for me that the `Turtl server` URL under `Advanced settings` on the login screen is `https://apiv3.turtlapp.com` ?

**Comment by orthecreedence** [comment] 2018-10-05 05:20
I'm at a loss for how that url could work in the browser but not when trying to connect through the Turtl client, so I'm hoping that somehow the value in that "Turtl server" box is incorrect.

**Comment by MaxCreeger32** [comment] 2018-10-05 07:12
yes that's this url : 
![image](https://user-images.githubusercontent.com/31531494/46521037-8655bb00-c87e-11e8-94ef-578b61136318.png)

I really undesrtand your loss , this is really strange for me too.

**Comment by orthecreedence** [comment] 2018-10-06 16:05
Can you attach your entire log file to this ticket?

**Comment by MaxCreeger32** [comment] 2018-10-08 07:11
here it is 
[core.log](https://github.com/turtl/tracker/files/2454942/core.log)

**Comment by orthecreedence** [comment] 2018-10-09 18:25
Getting more reports of this, but still not able to reproduce and the logs aren't giving much info at all. I'll try to do some digging tonight.

**Comment by orthecreedence** [comment] 2018-10-11 02:03
@MaxCreeger32 I just released a new desktop version (https://github.com/turtl/desktop/releases/tag/v0.7.1-logfix) that will actually enable the debug logging you set in the config file. This might help narrow down some issues. Can you please try again with this release and upload your log again?

Thanks!

**Comment by MaxCreeger32** [comment] 2018-10-16 06:36
here it is 
[core.log](https://github.com/turtl/tracker/files/2454942/core.log)

**Comment by MaxCreeger32** [comment] 2018-10-16 06:37
sorry for the delay, here is another fresh log : 
[core.log](https://github.com/turtl/tracker/files/2481699/core.log)

**Comment by orthecreedence** [comment] 2018-10-16 06:48
Thanks! Sorry to be a nuisance, can you set your log level to `trace` in `config.yaml` and send me another core.log?

```
logging:
  level: 'trace'
```

**Comment by MaxCreeger32** [comment] 2018-10-16 06:57
I have set the trace level and now I can see that there it does not auto-detect proxy configuration : 
`2018-10-16T08:50:41 - [TRACE][hyper::client] send method=Post, url="https://apiv3.turtlapp.com/auth", client=Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 10, nanos: 0 }), write_timeout: None, proxy: None }` as it is said here that there is no proxy. 
I will try to see where we can config some proxy, I think we have some tools that need proxy configuration, so I will try to see how they are set. 
here is the whole file with the trace level : 
[core.log](https://github.com/turtl/tracker/files/2481744/core.log)

**Comment by orthecreedence** [comment] 2018-10-16 07:36
Ok, I think I see what's happening.

In the old version, all the connections ran through Node-webkit, which is a wrapper around the chrome browser. Chrome automatically detects system-wide proxy settings and applies them to all outgoing connections. Node-webkit respected this, and just automatically used your proxy settings.

Now, the connections are being made through the turtl core, not the browser wrapper, and the browser isn't sending the proxy information into the core. I think what I need to do is see if there's an explicit way of getting the system proxy from the desktop app and pass them into the core as part of the settings.

Thanks for helping me narrow this down. I hope to have this working for you soon.

**Comment by MaxCreeger32** [comment] 2018-10-16 08:51
Ok I understand why it was working on the old version... great thanks for your hunt and your reactivity.

**Comment by orthecreedence** [comment] 2018-10-19 05:43
@MaxCreeger32 Please try this new release: https://github.com/turtl/desktop/releases/tag/v0.7.1-proxyfix

I think it might fix the connection issue!

**Comment by orthecreedence** [comment] 2018-10-19 23:25
Note that these latest changes (use `reqwest` instead of `hyper`, which in turn uses a later version of hyper `0.12.12`) causes the app to hang in Android when making any outbound HTTP requests (including POSTing the `/auth` endpoint). In other words, this may fix the desktop proxy issue, but it severely cripples the app on android. I either need to roll back and figure out another method of proxying the connections, or figure out a way to make the mio/tokio/hyper/reqwest stack work.

**Comment by MaxCreeger32** [comment] 2018-10-23 11:34
Hello I had time only today to do install this fix-version , but i still have the problem. 
I have seen the config parameter for the proxy, but it does nothing better. here is the core.log. 
I am really sorry to bother you again with that.
[core.log](https://github.com/turtl/tracker/files/2505916/core.log)

**Comment by orthecreedence** [comment] 2018-10-23 16:37
Weird, it looks like the proxy is not being sent into the core. Can you try something for me?

Open the desktop app, type `ctrl+shift+k`, select the Console tab, and paste this and hit enter:

```javascript
turtl.core.send('app:get-config').then(function(config) { console.log(JSON.stringify(config, null, 2)); })
```

and let me know the output? Thanks!

**Comment by MaxCreeger32** [comment] 2018-10-30 12:18
Sorry for the delay
With your command, the proxy is set correctly... but i don't know why it does want to use it or 
here is what I have : 
```json
{
  "api": {
    "client_version_string": "desktop/0.7.1",
    "endpoint": "https://apiv3.turtlapp.com",
    "proxy": "proxy.mipih.net:3128",
    "v6": {
      "endpoint": "https://api.turtlapp.com/v2"
    }
  },
  "data_folder": "C:\\Users\\datas\\AppData\\Roaming\\Turtl\\core",
  "integration_tests": {
    "data_folder": "/tmp/turtl/integration",
    "login": {
      "password": "omgitsatest",
      "username": "testdata@turtlapp.com"
    },
    "v6_login": {
      "password": "juice",
      "username": "duck duck"
    }
  },
  "logging": {
    "file": "core.log",
    "level": "trace",
    "rotation": {
      "keep": 3,
      "size": 1048576
    }
  },
  "messaging": {
    "events": "inproc://turtl-events",
    "reqres": "inproc://turtl-req",
    "reqres_append_mid": false
  },
  "openssl_cert_file": "C:\\Program Files\\Turtl\\resources\\app\\scripts\\resources\\cacert.pem",
  "sync": {
    "enable_files_incoming": true,
    "enable_files_outgoing": true,
    "enable_incoming": true,
    "enable_outgoing": true,
    "poll_timeout": 25
  },
  "wrap_errors": false
}
```

For information here is the Javascript stack trace  : 

```
login error:  Error: https://apiv3.turtlapp.com/auth: an error occurred trying to connect: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. (os error 10060)
    at derr (_functions.js:167)
    at Omni.<anonymous> (login.js:117)
    at tryCatch1 (bluebird.js:5004)
    at Promise$_callHandler [as _callHandler] (bluebird.js:2562)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (bluebird.js:2576)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (bluebird.js:2739)
    at Promise$_settlePromises [as _settlePromises] (bluebird.js:2882)
    at Promise$_rejectPromises [as _rejectPromises] (bluebird.js:2875)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (bluebird.js:150)
    at Async$consumeFunctionBuffer (bluebird.js:113)
(anonymous) @ login.js:117
tryCatch1 @ bluebird.js:5004
Promise$_callHandler @ bluebird.js:2562
Promise$_settlePromiseFromHandler @ bluebird.js:2576
Promise$_settlePromiseAt @ bluebird.js:2739
Promise$_settlePromises @ bluebird.js:2882
Promise$_rejectPromises @ bluebird.js:2875
Async$_consumeFunctionBuffer @ bluebird.js:150
Async$consumeFunctionBuffer @ bluebird.js:113
Promise$_Scheduler @ bluebird.js:4210
```

**Comment by j-santander** [comment] 2018-11-01 12:07
@orthecreedence I'm having the same problem, I'd like to use turtl behind a proxy.
I've not the faintest idea about rust, but I did a little debugging and I believe the problem is in `core/src/api.rs` line 103. It's currently:

```rust
                if let Some(proxy_cfg) = x {
                    debug!("api::call() -- req: using proxy: {}", proxy_cfg);
                    client_builder = client_builder.proxy(Proxy::http(format!("http://{}", proxy_cfg).as_str())?);
                }
```
but it should probably be:
```rust
                if let Some(proxy_cfg) = x {
                    debug!("api::call() -- req: using proxy: {}", proxy_cfg);
                    client_builder = client_builder.proxy(Proxy::http(format!("http://{}", proxy_cfg).as_str())?);
                    client_builder = client_builder.proxy(Proxy::https(format!("http://{}", proxy_cfg).as_str())?);
                }
``` 
or
```rust
                if let Some(proxy_cfg) = x {
                    debug!("api::call() -- req: using proxy: {}", proxy_cfg);
                    client_builder = client_builder.proxy(Proxy::all(format!("http://{}", proxy_cfg).as_str())?);
                }
``` 

In your code, you're instructing the HTTP client library to use a proxy for HTTP requests, but typically that does not apply to HTTPS requests.

Please find attached a small patch file [proxy.patch.gz](https://github.com/turtl/tracker/files/2538438/proxy.patch.gz). Hope this helps. Let me know if you would like a pull request instead.

BTW. I'm slightly confused about where do I need to add the proxy configuration, as I found four different places: 
```
./build/config.js
./build/config.yaml
./config/config.js
./config/config.live.js
```
The one that seems to win is `build/config.js`

Regards
Julian

**Comment by orthecreedence** [comment] 2018-11-05 16:37
This is very strange. If the proxy is set into `config.api.proxy` then it should be used. @MaxCreeger32 can you try this newest release (remove any previous version of Turtl before installing)? https://github.com/turtl/desktop/releases/tag/v0.7.2.2

Give that another try. I wonder if updating the DLL directly did not work and updating everything at once will work. Thanks for your patience.

**Comment by orthecreedence** [comment] 2018-11-09 22:56
Apparently this is still an issue:

```
2018-11-08T07:57:21 - [INFO][turtl_core::messaging] messaging::start() -- main loop
2018-11-08T07:57:21 - [INFO][turtl_core::messaging] messaging::ui_event() -- messaging:ready
2018-11-08T07:57:22 - [INFO][turtl_core::dispatch] dispatch(1): app:api:set-endpoint
2018-11-08T07:57:22 - [INFO][turtl_core::dispatch] dispatch(2): app:api:get-endpoint
2018-11-08T07:57:22 - [INFO][turtl_core::dispatch] dispatch(3): app:api:get-old-endpoint
2018-11-08T07:57:54 - [INFO][turtl_core::dispatch] dispatch(4): app:api:set-endpoint
2018-11-08T07:57:54 - [INFO][turtl_core::dispatch] dispatch(5): app:api:set-old-endpoint
2018-11-08T07:57:54 - [INFO][turtl_core::dispatch] dispatch(6): user:login
2018-11-08T07:57:54 - [INFO][turtl_core::models::user] user::generate_auth() -- generating v0 auth
2018-11-08T07:57:55 - [DEBUG][turtl_core::api] api::req() -- begin: POST /auth
2018-11-08T07:57:55 - [DEBUG][turtl_core::api] api::call() -- req: using proxy: XX.XX.XX.254:8080
2018-11-08T07:57:55 - [DEBUG][turtl_core::api] api::call() -- req: POST https://apiv3.turtlapp.com/auth
2018-11-08T07:58:16 - [DEBUG][turtl_core::api] api::call() -- call error: {"err":{"message":"https://apiv3.turtlapp.com/auth: an error occurred trying to connect: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat. (os error 10060)","type":"generic"},"file":"src\\api.rs","line":115,"wrapped":true}
2018-11-08T08:00:28 - [INFO][turtl_core::dispatch] dispatch(7): app:get-log
2018-11-08T08:03:41 - [INFO][turtl_core::dispatch] dispatch(8): app:get-log
```

Another user reported they are unable to connect, even though the app is "using" the proxy (`req: using proxy: XX.XX.XX.254:8080`)

I guess the hunt continues.

**Comment by j-santander** [comment] 2018-11-10 13:04
@orthecreedence not sure if you missed my comment above. 
I've submitted it now as a pull request. I've tested it for my set-up (both making it go through a squid forward proxy I set up on a docker container here at home, but also tested through my corporate proxy) and it is working.

**Comment by orthecreedence** [comment] 2018-11-11 18:51
@j-santander Wow I did completely miss your comment, sorry! I'll merge your PR (thank you).

Also, regarding the config, I would use `build/config.yaml` and set `api.proxy`:

```yaml
api:
  ...
  proxy: "1.2.3.4:8080"
  ...
```

That said, I just realized this is somewhat incomplete as it is now. Once this is set, communication with the Turtl API will happen via proxy, however displaying images in the UI will use the system-wide proxy (if one is set). I think what I really need to do is add a "proxy" input box to the Advanced Settings part of the login page that would set the proxy both for the Turtl API *and* the interface. I'll create a new issue for this.

**Comment by orthecreedence** [comment] 2018-11-12 03:15
Just added https://github.com/turtl/tracker/issues/237. Once complete, this would add complete proxy support.

I've just created a new release now with @j-santander's changes merged in:

https://github.com/turtl/desktop/releases/tag/v0.7.2.3-proxy-fix

Can you give it a try and let me know how it works?

**Comment by b-schliessmann** [comment] 2018-11-12 07:19
Hello everyone

I've previously contacted the Turtl dev team by e-mail because I was facing the same issue (the log excerpt above is mine). In the reply, I was asked to provide details on my proxy configuration if possible. To keep things simple, I figured I'd do it here.

I'm accessing a squid 3.5.12 HTTP(S) proxy, configured in Windows 7 using a PAC (proxy autoconfiguration) script.

I'm happy to report, however, that the v0.7.2.3-proxy-fix release fixed the issue for me. Thanks for the quick fix! :+1: 

If there is any more testing needed, I'd be happy to provide assistance.

Thanks and best regards

Björn

**Comment by orthecreedence** [comment] 2018-11-13 21:16
Thanks, Björn!

**Closed as completed** 2018-11-28 04:35 UTC
Labels: type:bug, project:core, status:help-wanted, priority:high

**Comment by b-schliessmann** [comment] 2018-12-07 10:29
One last comment: I just downloaded and installed 0.7.2.5 from the website -- still working. Thanks again!
