### ISSUE TITLE
Minimize to tray on close in Ubuntu 18.04.2

### ISSUE THREAD

**Issue by tryfon** [turtl/tracker#291] opened 2019-02-22 16:12 UTC
I am using Ubuntu 18.04.2 and when I click the minimize button the app gets minimized and remains on the vertical launchers dock on the left and as a consequence it always gets in the way when I use Alt+Tab or the "Activities overview" feature. If instead I click the close button the app just quits! 
I would like it to behave similarly to applications such as Skype for example where when I click the close button the application minimizes to tray and does not appear anymore on the launchers dock, just the icon on the tray bar on the top right remains (if I need to quit I do it through there or through the menu).
By the way I had the same issue with Thunderbird and I had to resort to an external application to make it happen (I ended up to birdtray after many unsuccessful attempts with other tools). I think this should be a default behavior, or at least configurable.

**Comment by orthecreedence** [comment] 2019-02-24 18:54
Hi! This is probably a duplicate of https://github.com/turtl/tracker/issues/67 (minimize-to-tray has not been implemented for the desktop app yet).

**Closed as completed by orthecreedence** 2019-02-24 18:54 UTC

**Comment by tryfon** [comment] 2019-02-25 08:12
Yes, I had seen #67 before posting, but the description doesn't match what I am talking about.
