### ISSUE TITLE
Markdown Links to Local Paths (file:///)

### ISSUE THREAD

**Issue by StephenFUSM** [turtl/tracker#387] opened 2021-02-05 15:48 UTC
Is there a way to implement linking to files on the local machine rather than adding them as attachments to notes?  For instance, using a markdown link such as `[Click Here](file:///C:/Username/Documents/MyFile.pdf)` to reference to open the file in it's native program (Adobe, Word, etc.).  Or even if not with markdown links, maybe just add a way to link to the file rather than upload and encrypt the contents.

My idea was to use Turtl as a type of efficient file browser where I could organize all my work reports, datasheets, etc.  However, I know that this idea may conflict with the encryption and security methodology of Turtl.  Let me know your thoughts and I'm willing to help implement this if need be.

**Comment by orthecreedence** [comment] 2021-02-05 17:49
Hello. I think you might be going outside the realm of what the app was designed for. It's been a while since I've explored it, but what you want sounds similar to [Tagspaces](https://www.tagspaces.org/), which I've always kind of thought of as "Turtl for file management." I haven't personally used it in many years, but always hear good things.

As far as using Turtl for local file management, it's out of scope of the project and would likely need to be its own fork. The security/privacy aspects are a core feature of Turtl and introducing any ambiguity as to whether something is encrypted or not would be in conflict with this goal.

**Closed as completed by orthecreedence** 2021-02-05 17:49 UTC

**Comment by StephenFUSM** [comment] 2021-02-05 19:14
Wow, thank you for the redirect to Tagspaces!  This seems like exactly what I was looking for.  I kind of knew I was going out on a limb requesting the local file links.  Thanks!

**Comment by orthecreedence** [comment] 2021-02-05 21:20
Happy to help, I hope Tagspaces works for you!
