### ISSUE TITLE
FDroid OpenSSL issue at registration

### ISSUE THREAD

**Issue by thepra** [turtl/tracker#281] opened 2019-01-30 18:09 UTC
After entering email and passphrase and proceeding for the registration the following error is notified: `There was a problem saving that account: An error in the OpenSSL library: certificate verify failed`

**Comment by akoshpinter** [comment] 2019-01-31 15:48
Installed from f-droid, the same error happens. Using Android 9.

**Comment by orthecreedence** [comment] 2019-01-31 17:40
Closing as a duplicate of #276

**Closed as completed by orthecreedence** 2019-01-31 17:40 UTC
